name = "TuringPosteriorDB"
uuid = "ac896df5-8883-4c42-b055-604fc742cf6a"
authors = ["Jason-Pekos"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
